app/controllers/application_controller.rb

Remove browser version guard restriction added by Rails as default.
This was introduced in Rails 7.2 but is too restrictive and blocks too many browser versions.

Remove browser version guard restriction

---

.github/workflows/ci.yml
_typos.toml
app/views/layouts/_dfe_footer.html.erb

This uses the [typos] spelling checker to check the codebase as part of the build.
[typos]: https://github.com/crate-ci/typos

Check for misspellings and typos

---

app/models/category.rb
spec/fixtures/vcr_cassettes/Category/solutions_ordering/orders_solutions_alphabetically_by_title.yml
spec/models/category_spec.rb

JIRA ticket - https://dfedigital.atlassian.net/jira/software/projects/FB/boards/258?selectedIssue=FB-149
When a user visits a Category page, frameworks (buying options) belonging to that category should be displayed in alphabetical order of their title.
Contentful doesn't support ordering results by a text field, so the ordering is done in Rails.

FB-149 Display solutions on category page in alphabetical order

---

app/views/solutions/show.html.erb

The backlink on the solution show page is currently set to its category page.
If a user selects some subcategory filters on the category page, then navigates to a solution page and clicks back, they will lose all the filters they selected.
This PR fixes that by setting the back link to the referer, with the category page as the fallback.

Set back link on solution page to referer

---

app/assets/stylesheets/application.sass.scss
app/controllers/application_controller.rb
app/controllers/categories_controller.rb
app/views/shared/_dfe_header.html.erb
app/views/shared/_dfe_homepage_header.html.erb
app/views/shared/_dfe_logo_and_menu.html.erb

- Homepage Header Description - Font size: H3, bold. Colour: CCD8E1
- Changes to the :show_search locals check to show the search bar for all other pages except the homepage on the top right portion of the header

- Design changes to FB-127 

---

app/views/solutions/show.html.erb

This is a quick fix for a demo today. We will add the correct link in a separate PR.

Add placeholder link on solution details page

---

app/assets/stylesheets/application.sass.scss
app/controllers/pages_controller.rb
app/models/page.rb
app/views/categories/show.html.erb
app/views/pages/show.html.erb
app/views/shared/_dfe_sidebar.html.erb
app/views/shared/_related_actions.html.erb
app/views/solutions/show.html.erb
config/locales/en.yml
config/routes.rb
spec/fixtures/vcr_cassettes/Page/_find_by_slug_/when_page_does_not_exist/raises_ContentfulRecordNotFoundError.yml
spec/fixtures/vcr_cassettes/Page/_find_by_slug_/when_page_exists/returns_the_page.yml
spec/fixtures/vcr_cassettes/Page/_initialize/sets_the_attributes.yml
spec/models/page_spec.rb

This PR adds a new `Page` model corresponding to the same in Contentful. It includes the following:
- Page model and specs
- PagesController and show page
- Refactored sidebar logic to display sidebar content specific to each Page
- The existing placeholder sidebar content for categories and solutions has been moved to a new partial. This needs to be updated to use real content but that's outside the scope of this PR.

Add support for content pages

---

app/helpers/application_helper.rb
app/views/solutions/show.html.erb
config/locales/en.yml

The link to a solution's website was added in a hurry for a demo. This PR adds the missing url.
It assumes the url exists but we need to add a `required` constraint on the url field in the Solution model in Contentful.

Use the solution url on its show page link

---

app/assets/stylesheets/application.sass.scss
app/views/categories/_category.html.erb

JIRA ticket - https://dfedigital.atlassian.net/jira/software/projects/FB/boards/258?selectedIssue=FB-161
- Fix category tile height
- Truncate title and description text when it's more than 5 lines long.
- Hyphenate long words
- Fix left alignment of grid

FB-161 Fix category tile height and truncate text when it's too long

---

app/views/shared/_dfe_logo_and_menu.html.erb
config/locales/en.yml

This PR updates the navigation links in the header as per the latest design.
- Remove links we no longer need
- Update Guidance link

Update nav links in header

---

app/assets/stylesheets/application.sass.scss

Small tweaks to category tiles and grid gaps as per latest designs:
- Remove fixed tile height to allow smaller tiles for short content.
- Increase gaps between tiles

Update tile height and grid gaps as per latest designs

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/views/pages/show.html.erb

Set the default back link to the root path. The back link should work even if a page doesn't have a custom back link set.
Set back link for content pages.

Update back links

---

app/assets/stylesheets/application.sass.scss
app/views/categories/index.html.erb
app/views/layouts/application.html.erb
app/views/layouts/homepage.html.erb
app/views/layouts/pages.html.erb
app/views/layouts/search.html.erb
app/views/search/index.html.erb
app/views/shared/_dfe_footer.html.erb
app/views/shared/_dfe_homepage_header.html.erb
app/views/shared/_dfe_logo_and_menu.html.erb
app/views/shared/_dfe_narrow_search_box.html.erb
app/views/shared/_dfe_search.html.erb
app/views/shared/_dfe_sidebar.html.erb
config/locales/en.yml
public/404.html
public/500.html
public/application.css

This PR fixes a number of design and markup issues: 
- Remove extra H1 tags
- Add H1 tag on pages where it's missing
- Replace H2 with H1 for page titles
- Remove unused tags
- Fix alignment issues
- Fix current link highlighting in header nav
- Update layouts and styles to match latest designs
- Add empty state text for search results page

Fix design issues

---

app/views/layouts/pages.html.erb
config/locales/en.yml

A couple of fixes based on the walkthrough conversation:
- Hyphenate "Dfe-approved"
- Restore back link on content pages

Fixes: copy and back link

---

app/models/contentful_client.rb
config/initializers/contentful.rb

As we move towards launch, we need to be able to use separate environments in Contentful.
- Add configuration to specify a Contentful environment via an environment variable
- Use `master` environment by default (matching the default in Contentful)

Add ability to specify Contentful environment

---

app/assets/stylesheets/application.sass.scss
app/views/categories/index.html.erb

Couple of quick design fixes:
- Fix category card content alignment
- Move procurement support link below all category cards

Design fixes

---

app/views/shared/_dfe_base.html.erb
app/views/shared/_ms_clarity.html.erb

Use an environment variable to specify the MS Clarity project ID. This gives us finer control over configuring Clarity per environment.

Use environment variable to enable MS Clarity

---

config/application.rb
lib/real_ip.rb
spec/lib/real_ip_spec.rb

JIRA ticket - https://dfedigital.atlassian.net/browse/FB-247
Add middleware to set `HTTP_X_REAL_IP` for anonymised user journey tracking in dfe analytics
The `dfe-analytics` gem relies on the `X-REAL-IP` header to create an `anonymised_user_agent_and_ip` attribute in tracked events. This is useful for tracking user journeys without PII. 
However, we don't have the `X-REAL-IP` header on Heroku.
This PR defines a new middleware to set `X-REAL-IP` to the first value in `X-Forwarded-For`.

[FB-247] Add middleware to set HTTP_X_REAL_IP

---

app/views/shared/_dfe_logo_and_menu.html.erb
config/locales/en.yml
public/404.html
public/500.html

- Removed navigation bar
- Home and Guidance no longer appear on the Homepage
- After change screenshot:

FB-234-Update the homepage to remove navigation and the guidance page

---

app/assets/javascripts/application.js
app/controllers/events_controller.rb
app/javascript/controllers/external_link_tracking_controller.js
app/views/shared/_dfe_base.html.erb
config/analytics_custom_events.yml
config/routes.rb
package.json
yarn.lock

JIRA ticket - https://dfedigital.atlassian.net/browse/FB-246
The` dfe-analytics` gem automatically tracks all pageviews within our website. However, if a user clicks on a link to an external site (e.g. a framework website or gov uk support page), those clicks are not automatically tracked.
This PR adds a way to track external link clicks - 
- Add Stimulus controller to listen for link clicks and track a custom event called `external_link_clicked`
- Add Rails controller to track events with `dfe-analytics`
- Open external links in new tab
- Add `rel` attributes to external links
Screenshot below shows a tracked event in BigQuery:

FB-246 Track external link clicks with dfe-analytics

---

app/helpers/application_helper.rb
app/javascript/controllers/external_link_tracking_controller.js
app/services/url_verifier.rb
app/views/solutions/show.html.erb
spec/features/solutions_spec.rb
spec/fixtures/vcr_cassettes/Solutions_pages/when_displaying_call_to_action_button/includes_the_usability_survey_URL_as_a_data_attribute.yml
spec/fixtures/vcr_cassettes/Solutions_pages/when_displaying_call_to_action_button/includes_the_usability_survey_URL_with_service_and_return_url_params.yml

JIRA ticket - https://dfedigital.atlassian.net/browse/FB-230
- Add a link to a Usability Survey on the Solution show page.
- Clicking on the CTA button takes the user to the usability survey hosted on the GHBS website.
- The Solution url is included as an HMAC encoded string, which is verified by the GHBS app before redirecting the user to it
- CTA link is preserved so the user can copy the link for sharing
- Clicks are tracked as before in dfe-analytics
- Add specs

FB-230 Add link to Usability Survey on Solution show page

---

app/controllers/search_controller.rb
app/views/search/_full_width_search_box.html.erb
app/views/search/index.html.erb
app/views/shared/_dfe_narrow_search_box.html.erb
app/views/shared/_dfe_search.html.erb
config/locales/en.yml
spec/requests/search_spec.rb

JIRA ticket - https://dfedigital.atlassian.net/browse/FB-262
Add Search validation:
- Allow users to submit any search query, including empty searches and queries longer than the Contentful limit
- Show a "No search results" page with an appropriate error message
- Add tests

FB-262 Search validation

---

Gemfile
Gemfile.lock

We've been using a fork of the `dfe-analytics` gem. Now the official gem has our changes in a[ tagged release](https://github.com/DFE-Digital/dfe-analytics/blob/main/CHANGELOG.md#v1156-2025-04-30), so this PR switches to using that.

Switch dfe-analytics from fork to official gem

---

app/assets/stylesheets/application.sass.scss
config/locales/en.yml
public/application.css

Small copy fixes: 
- Remove periods from header and beta banner.
- Don't hyphenate long words on category tiles

Copy fixes

---

config/application.rb
config/environments/production.rb

When I implemented handling FaF redirect (https://github.com/DFE-Digital/find-a-buying-solution/pull/154), I added a host config to `application.rb` but this broke development. 
In this PR, I've moved the host config to `production.rb`.

Fix host config

---

app/assets/javascripts/application.js
app/controllers/events_controller.rb
app/javascript/controllers/engagement_tracking_controller.js
app/views/shared/_dfe_base.html.erb
config/analytics_custom_events.yml

JIRA ticket - https://dfedigital.atlassian.net.mcas.ms/browse/FB-253
- Add new Stimulus controller to track active engagement time per page
- Check every 10 seconds if the user has been active in the last 30 seconds
- Send the engagement data to the server once every minute

FB-253 Track active engagement time on each page

---

app/views/shared/_dfe_homepage_header.html.erb

https://dfedigital.atlassian.net/browse/FB-337
Add bottom padding to `<header>` instead of margin below the link to fix a spacing bug.

FB-337 Fix header bottom spacing bug on Safari

---

app/javascript/controllers/external_link_tracking_controller.js
app/views/solutions/show.html.erb
spec/features/solutions_spec.rb

JIRA ticket - https://dfedigital.atlassian.net/browse/FB-339
Safari is blocking all external link clicks because we intercept the click with JavaScript to capture the event in analytics.
This PR is an attempt to avoid that blocking by not calling `event.preventDefault()`.

FB-339 Open external links without preventing default click event

---

app/views/shared/_related_content.html.erb

FB-318-Related-Items-as-unordered-list
Issue: https://dfedigital.atlassian.net/browse/FB-318
FB-318-The related content is now coded as a unordered list without bullets

FB-318-The related content is now coded as a unordered list without bullets

---

app/assets/stylesheets/application.sass.scss
app/views/shared/_solutions.html.erb
app/views/solutions/index.html.erb

Issue: https://dfedigital.atlassian.net/browse/FB-319
Solution:
- Reduced the spacing between the buying options heading and the solutions.
- Also reduced the spacing between each solution being listed.
- Added bottom margin to each category listed in the all-buying-options page

FB-319 - Incorrect spacing on Buying options

---

app/assets/stylesheets/application.sass.scss
app/views/shared/_solutions.html.erb

Issue: https://dfedigital.atlassian.net/browse/FB-319
FB-319-Uneven spacing in each buying option - meantioned in https://dfedigital.atlassian.net/browse/FB-319?focusedCommentId=116055 has been fixed by taking the styling from the prototype https://ghbs-fabs-prototype-dd2d6f44aad8.herokuapp.com/v3/banking-laons/banking-loans
After fix:
The prototype css and styling has been applied to solutions
Check that the spacing is even int he solutions listed before the horizontal line and after it.

FB-319-Uneven spacing in each buying option

---

app/assets/stylesheets/application.sass.scss

Issue: https://dfedigital.atlassian.net/browse/FB-359
Added  $govuk-brand-colour (#1d70b8) as the dfe-header background-colour

FB 359 - Update the colour of the service to match new gov.uk frontend (#1d70b8)

---

app/assets/stylesheets/application.sass.scss
app/controllers/categories_controller.rb
app/controllers/solutions_controller.rb
app/views/layouts/application.html.erb

Issues
[https://dfedigital.atlassian.net/browse/FB-376](https://dfedigital.atlassian.net/browse/FB-376)
The [design](https://lucid.app/lucidspark/99574499-5a78-4da9-abf6-78207fd5de84/edit?view_items=Ycaye9V70d0_&invitationId=inv_04524c90-7810-4600-8a5b-3105bff9e0b6) can be found in lucid
Update: 
- Home Page hovers over any category tile it should appear as light blue. #1d70b8
- Category page -  page header background colour updated
- Details page -  page header background colour updated

Fb 376 - Update site to reflect new frontend colour scheme

---

app/views/categories/index.html.erb
config/locales/en.yml
spec/requests/categories_spec.rb

Issues
[https://dfedigital.atlassian.net/browse/FB-380](https://dfedigital.atlassian.net/browse/FB-380)
Update
Remove the ‘I need something else link’ from the homepage.

FB-380 -remove I need something else link from the homepage

---

app/assets/stylesheets/application.sass.scss
app/views/shared/_dfe_search_box.html.erb

Issues: https://dfedigital.atlassian.net.mcas.ms/browse/FB-361
Update
Background colour update in the search drop down from #FFFFFF to light blue #F4F8FB.  Also the background colour behind the search close icon X

FB-361 update background colour for search box in the header

---

app/assets/stylesheets/application.sass.scss
app/views/shared/_dfe_search_box.html.erb

Fix top search box for mobile
before
After

FB-361 css mobile fixes for the top search bar in the header

---

config/environments/production.rb
config/locales/en.yml
spec/features/solutions_spec.rb

Issue: https://dfedigital.atlassian.net/browse/FB-404
- The default CTA on all details pages now reads ‘Visit the provider’s website'
- changing production.rb on staging to pick up from en.yml file than contentful
- Added some TODO comments

FB-404 - Update the details page CTA button

---

config/environments/production.rb

Relates to: https://dfedigital.atlassian.net/browse/FB-221
In the production.rb , had to pass the the ENV["REDIS_URL"] and ssl_params.
RAILS_CACHE_EXPIRY_IN_SECONDS by default is set to "86400" seconds.
For testing purposes, RAILS_CACHE_EXPIRY_IN_SECONDS can be changed before making changes to contentful.

- testing redis config

---

app/helpers/markdown_helper.rb
spec/helpers/markdown_helper_spec.rb

Fix link font size in Markdown helper to be the same as body text.

Fix link font size in Markdown helper

---

app/views/categories/index.html.erb

PR: https://github.com.mcas.ms/DFE-Digital/find-a-buying-solution/pull/325
Issue: https://dfedigital.atlassian.net/browse/FB-461
ISSUE 1
Removed the spurious right chevron
Before
After
ISSUE 2
Scenario:
One offer without an image & no featured offer / One offer with an image & no featured offer
Expected:
Offers section NOT displayed on the homepage and Service Navigation section displayed at the top of the page

Fb 461 offers fixing issues

---

app/helpers/offer_helper.rb
app/views/categories/index.html.erb

Issue: 
https://dfedigital.atlassian.net/browse/FB-461
The offers section now displays the 'Offers' title and description along with the 'browse_all_offers' link on the homepage, even if there are no featured offers but there are other offers to show.
As you can see in the following image, although there are no featured offers to show either as a list/card, the offers section still shows up with Offers title , description and with the "Browse all offers' link.

FB-461 - offers section needs to show if offers>0 and featured_offers=0

---

app/controllers/categories_controller.rb
spec/fixtures/vcr_cassettes/Canonical_URLs/when_requesting_the_root_path/1_1_1.yml
spec/fixtures/vcr_cassettes/Categories_pages/GET_/displays_category_descriptions.yml
spec/fixtures/vcr_cassettes/Categories_pages/GET_/displays_category_titles.yml
spec/fixtures/vcr_cassettes/Categories_pages/GET_/does_not_display_categories_without_solutions.yml
spec/fixtures/vcr_cassettes/Categories_pages/GET_/includes_buying_options_section_heading.yml
spec/fixtures/vcr_cassettes/Categories_pages/GET_/sets_default_HTML_title_tag.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_3_offers_without_images/does_not_show_offer_images.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_3_offers_without_images/does_not_show_the_Browse_all_offers_link.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_3_offers_without_images/shows_all_offers_as_bullet_points.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_exactly_3_offers_with_images/does_not_show_the_Browse_all_offers_link.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_exactly_3_offers_with_images/shows_the_offers_section.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_more_than_3_offers_and_less_than_3_have_images/shows_all_offers_as_bullet_points.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_more_than_3_offers_and_less_than_3_have_images/shows_the_Browse_all_offers_link.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_more_than_3_offers_but_only_3_with_images/shows_the_Browse_all_offers_link.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_more_than_3_offers_but_only_3_with_images/shows_the_offers_section_with_3_offer_cards.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_no_offers/does_not_show_offers_in_the_service_navigation.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_no_offers/does_not_show_the_Browse_all_offers_link.yml
spec/fixtures/vcr_cassettes/Homepage_Offers_Section/when_there_are_no_offers/does_not_show_the_offers_section.yml

This won't always be energy for schools, so let's make it generic, by changing it from energy-for-schools to homepage-banner. For continuity, the new default can be overridden by an environment variable, HOMEPAGE_BANNER_SLUG.

FB-459 Change banner slug
