- .github/CODEOWNERS
This will make it easier for us to assign reviewers to pull requests.
> Add current team to CODEOWNERS file

- doc/deployment.md
We can add to this in the future as required.
> Add basic documentation of deployment

- app/assets/stylesheets/application.sass.scss
- app/controllers/application_controller.rb
- app/controllers/categories_controller.rb
- app/models/category.rb
- app/models/solution.rb
- app/views/categories/show.html.erb
- app/views/shared/_dfe_page.erb
- spec/fixtures/vcr_cassettes/Categories_pages/GET_/categories/_slug_with_subcategory_filters/when_form_is_submitted_with_selected_subcategories/keeps_the_checkboxes_selected_after_form_submission.yml
- spec/fixtures/vcr_cassettes/Categories_pages/GET_/categories/_slug_with_subcategory_filters/with_empty_subcategory_slugs_parameter/displays_all_solutions_in_the_category.yml
- spec/fixtures/vcr_cassettes/Categories_pages/GET_/categories/_slug_with_subcategory_filters/with_empty_subcategory_slugs_parameter/returns_a_successful_response.yml
- spec/fixtures/vcr_cassettes/Categories_pages/GET_/categories/_slug_with_subcategory_filters/with_specific_subcategory_slugs_parameters/only_displays_solutions_with_matching_subcategories.yml
- spec/fixtures/vcr_cassettes/Categories_pages/GET_/categories/_slug_with_subcategory_filters/with_specific_subcategory_slugs_parameters/returns_a_successful_response.yml
- spec/fixtures/vcr_cassettes/Category/_filtered_solutions/excludes_solutions_that_don_t_match_any_of_the_specified_subcategory_slugs.yml
- spec/fixtures/vcr_cassettes/Category/_filtered_solutions/filters_solutions_by_subcategory_slugs.yml
- spec/fixtures/vcr_cassettes/Category/_filtered_solutions/returns_all_solutions_when_subcategory_slugs_is_empty.yml
- spec/fixtures/vcr_cassettes/Category/_filtered_solutions/returns_all_solutions_when_subcategory_slugs_is_nil.yml
- spec/models/category_spec.rb
- spec/requests/categories_spec.rb
JIRA ticket - https://dfedigital.atlassian.net/jira/software/projects/FB/boards/258?selectedIssue=FB-126
- Add subcategory filter checkboxes to the category page.
- When subcategories are selected and applied, only solutions belonging to those subcategories are displayed on the category page.
- Some updates have been made to the styling of the solutions based on a new design.
> FB-126 Subcategory filters

- app/assets/stylesheets/application.sass.scss
- app/views/layouts/application.html.erb
> - Sidebar fix for empty content

- app/assets/stylesheets/application.sass.scss
- app/controllers/categories_controller.rb
- app/views/categories/_filter_labels.html.erb
- app/views/categories/show.html.erb
- config/locales/en.yml
JIRA Ticket - https://dfedigital.atlassian.net/jira/software/projects/FB/boards/258?selectedIssue=FB-151
Display an active label for each selected subcategory filter.
Labels can be clicked to remove filters.
Add a "Clear all filters" link to remove all filters at once.
> FB-151 Display active labels for selected subcategory filters

- app/assets/javascripts/application.js
- app/javascript/application.js
- package.json
- Merged app/javascript into app/assets/javascripts into one appliction.js file
- Made the relavent refactoring changes to the path in package.json file
> Merged all js into one file

- app/assets/stylesheets/application.sass.scss
- app/controllers/search_controller.rb
- app/models/category.rb
- app/models/solution.rb
- app/views/categories/show.html.erb
- app/views/layouts/search.html.erb
- app/views/search/_full_width_search_box.html.erb
- app/views/search/index.html.erb
- app/views/shared/_dfe_search.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/fixtures/vcr_cassettes/Category/_search/returns_categories_matching_the_query.yml
- spec/fixtures/vcr_cassettes/Solution/_search/returns_solutions_matching_the_query.yml
- spec/models/category_spec.rb
- spec/models/solution_spec.rb
JIRA Ticket - https://dfedigital.atlassian.net/browse/FB-139
Users should be able to search for buying options based on keywords.
This PR implements search across Categories and Solutions (which includes frameworks and other buying options). This is a simple first iteration which searches across all fields in each model.
> FB-139 Implement search

- app/models/category.rb
- spec/fixtures/vcr_cassettes/Categories_pages/GET_/displays_category_summaries.yml
- spec/fixtures/vcr_cassettes/Categories_pages/GET_/displays_category_titles.yml
- spec/fixtures/vcr_cassettes/Categories_pages/GET_/includes_buying_options_section_heading.yml
- spec/fixtures/vcr_cassettes/Category/_all/fetches_categories_in_alphabetical_order.yml
- spec/models/category_spec.rb
- spec/requests/categories_spec.rb
JIRA ticket - https://dfedigital.atlassian.net/jira/software/projects/FB/boards/258?selectedIssue=FB-161
Display categories on the homepage in alphabetical order of title.
> FB-161 Display categories in alphabetical order

- app/views/shared/_dfe_base.html.erb
- public/404.html
- public/500.html
Add missing `lang` attribute in all html files.
> Add missing lang attribute in all html files

- app/views/shared/_dfe_base.html.erb
Remove duplicate stylesheet tag
> Remove duplicate stylesheet tag

- app/models/page.rb
- app/models/subcategory.rb
- Remove category attribute from Subcategory model
- Remove breadcrumbs attribute from Page model
> Remove unused attributes from models

- Gemfile
- Gemfile.lock
- script/export-to-csv
It was required once, and might be useful again.
> Add a script to export the structure to a CSV file

- app/views/shared/_dfe_logo_and_menu.html.erb
- config/locales/en.yml
- public/404.html
- public/500.html
Remove About us link from header.
> Remove About us link from header

- config/locales/en.yml
- public/404.html
- public/500.html
Use Title case for site title "Get Help Buying for Schools" everywhere.
> Fix: Use Title case for site title

- app/views/solutions/index.html.erb
> - Fixes the sidebar heading spacing

- Gemfile
- Gemfile.lock
- lib/tasks/contentful.rake
This PR adds a rake task to import [JSON data from Find a Framework](https://find-dfe-approved-framework.service.gov.uk/frameworks). 
You will need to set environment variables called `CONTENTFUL_CMA_TOKEN` (which you can get from the CMA Tokens page in Contentful) and `CONTENTFUL_SPACE_ID` (for the space into which you want to import the data).
> Add rake task to import Find a Framework data into Contentful

- app/assets/stylesheets/application.sass.scss
- app/views/solutions/index.html.erb
Issue: https://dfedigital.atlassian.net/browse/FB-140
> FB-140 - Grouping and spacing changes for "All buying options" page

- app/views/shared/_dfe_base.html.erb
- app/views/shared/_ms_clarity.html.erb
https://dfedigital.atlassian.net.mcas.ms/browse/FB-236
Add MS Clarity JS snippet in head only in production.
> FB-236 Add Microsoft Clarity for user research

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/errors/contentful_record_not_found_error.rb
- app/helpers/application_helper.rb
- app/models/category.rb
- app/models/page.rb
- app/models/solution.rb
- config/initializers/rollbar.rb
- config/sidekiq.yml
- spec/fixtures/vcr_cassettes/Solution/_find_by_slug_/when_solution_does_not_exist/raises_ContentfulRecordNotFoundError.yml
- spec/fixtures/vcr_cassettes/Solution/_find_by_slug_/when_solution_exists/returns_the_solution.yml
- spec/models/category_spec.rb
- spec/models/page_spec.rb
- spec/models/solution_spec.rb
JIRA ticket - https://dfedigital.atlassian.net/browse/FB-184
- Add Rollbar gem and config
- Report Contentful and other errors
- Update tests
> FB-184 Add error monitoring with Rollbar

- app/views/solutions/index.html.erb
Issue: https://dfedigital.atlassian.net/browse/FB-272
FB-272-Hide expiry date and provider when this information is unavailable for the buying option
> FB-272-Hide expiry date and provider when this information is unavailable for the buying option

- config/application.rb
- lib/faf_domain_redirect.rb
- spec/lib/faf_domain_redirect_spec.rb
JIRA ticket - https://dfedigital.atlassian.net/browse/FB-202
Add a Rack middleware to redirect requests from the Find a Framework domain to root.
> FB-202 Redirect requests from Find a Framework domain to root

- app/controllers/application_controller.rb
- config/initializers/rollbar.rb
JIRA ticket - https://dfedigital.atlassian.net/browse/FB-297
Don't report 404s to Rollbar because it's too noisy.
> FB-297 Don't report 404s to Rollbar

- lib/tasks/contentful.rake
Add rake task to check Contentful solution urls
> Add rake task to check Contentful solution urls

- app/assets/stylesheets/application.sass.scss
- app/views/categories/index.html.erb
- app/views/layouts/all_buying_options.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/pages.html.erb
- app/views/layouts/search.html.erb
- app/views/shared/_dfe_beta_banner.html.erb
- app/views/shared/_dfe_footer.html.erb
- app/views/shared/_dfe_header.html.erb
- app/views/shared/_dfe_homepage_header.html.erb
- app/views/shared/_related_content.html.erb
- app/views/solutions/index.html.erb
- config/locales/en.yml
- public/404.html
- public/500.html
Various UI improvements, fixes and copy updates.
https://dfedigital.atlassian.net/browse/FB-279
- Fix spacing in homepage header
- Fix font sizes
- Fix styling for all buying options link
- Fix left alignment of homepage header text on mobile
- Fix copy
- Fix style of procurement_support link
- Fix beta banner style
- Increase homepage search box height
- Fix footer links spacing
- Fix styling of related content
- Update privacy link in footer
> UI improvements

- app/assets/stylesheets/application.sass.scss
- app/models/category.rb
- app/views/categories/show.html.erb
- app/views/search/index.html.erb
- app/views/shared/_dfe_narrow_search_box.html.erb
- spec/fixtures/vcr_cassettes/Category/_subcategories/returns_an_array_of_Subcategory_objects_with_titles_in_alphabetical_order.yml
- spec/fixtures/vcr_cassettes/Category/_subcategories/returns_subcategories_in_alphabetical_order_by_title.yml
- spec/models/category_spec.rb
JIRA tickets:
- https://dfedigital.atlassian.net/browse/FB-280
- https://dfedigital.atlassian.net/browse/FB-282
Updates:
- Header - fix search position
- Subcategory Filters in alphabetical order
- Category name - background - remove blue line
- Fix Buying options + description - spacing
- Use chevron card designs for List of buying options
- Fix inconsistent spacing - buying options lists, lines and texts
- Use single column layout for search results page
> FB-280 & FB-282 Category and search page UI fixes

- app/views/solutions/show.html.erb
- config/locales/en.yml
- spec/features/solutions_spec.rb
- spec/fixtures/vcr_cassettes/Solutions_pages/GET_/solutions/_slug/When_the_solution_has_no_expires.yml
- spec/fixtures/vcr_cassettes/Solutions_pages/GET_/solutions/_slug/displays_provider_and_expires_when_the_solution_has_them.yml
Issue: https://dfedigital.atlassian.net/browse/FB-303
> FB-303-Add provider and expiry date information to details pages

- app/views/search/index.html.erb
JIRA ticket - https://dfedigital.atlassian.net/browse/FB-282
Fix markup of search results
> FB-282 Fix markup of search results

- .github/workflows/ci.yml
- app/assets/javascripts/application.js
- app/javascript/controllers/engagement_tracking_controller.js
- app/javascript/controllers/external_link_tracking_controller.js
- bin/eslint
- eslint.config.mjs
- package.json
- yarn.lock
- Add JavaScript linting with ESLint. Run with `yarn lint`.
- Add to CI
> Add JavaScript linting

- package.json
- yarn.lock
Fix for https://github.com/DFE-Digital/find-a-buying-solution/security/dependabot/18
> Upgrade brace-expansion to fix security vulnerability

- package.json
- yarn.lock
I used the wrong version in the previous PR - https://github.com/DFE-Digital/find-a-buying-solution/pull/195
> Upgrade brace-expansion to v2.0.2

- app/views/solutions/show.html.erb
- spec/features/solutions_spec.rb
- spec/fixtures/vcr_cassettes/Solutions_pages/when_displaying_call_to_action_button/sets_the_CTA_button_href_to_the_solution_url.yml
JIRA ticket - https://dfedigital.atlassian.net/browse/FB-345
- Replace usability survey link on solution page with link to solution url
- Update specs
> PAY-345 Replace usability survey link on solution page with link to solution url

- app/views/layouts/pages.html.erb
- public/404.html
- public/500.html
- public/application.css
- public/application.js
issues
https://dfedigital.atlassian.net/browse/FB-363
Update:
Update branding for static pages
404 page - update the header, service navigation and footer
500 page  update the header, service navigation and footer
Terms and conditions-  update service navigation
Accessibility statement - update service navigation
> Fb 363 Update header and footer for static pages

- app/assets/stylesheets/application.sass.scss
Update heigh of search box to fox css issue
Before
After
> FB-361 fix mobile search box height on the homepage

- app/assets/stylesheets/application.sass.scss
- app/helpers/application_helper.rb
- app/views/shared/_dfe_homepage_header.html.erb
- app/views/shared/_dfe_logo_and_menu.html.erb
- app/views/shared/_dfe_service_navigation.html.erb
- config/locales/en.yml
JIRA ticket - https://dfedigital.atlassian.net/browse/FB-443
Add a new service navigation component. See screenshots below:
> FB-443 New service navigation component

- Gemfile.lock
Fix for https://github.com/DFE-Digital/find-a-buying-solution/security/dependabot/21
Dependabot's original PR got stuck in a loop - https://github.com/DFE-Digital/find-a-buying-solution/pull/316
> Upgrade rexml to 3.4.4 to fix security issue 
